name: Run Tests Before Merge

on:
    pull_request:
        branches:
            - production
            - development

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v3

            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 18
                  cache: "pnpm"

            - name: Install Dependencies
              run: pnpm install

            - name: Run Tests
              run: pnpm test

            - name: Run Build
              run: pnpm build
